// <auto-generated />
namespace CarFinder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _827151016amnothing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_827151016amnothing));
        
        string IMigrationMetadata.Id
        {
            get { return "201508271416372_[827151016amnothing]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
