// <auto-generated />
namespace CarFinder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _8271sdfsdfsd5329pmnothing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_8271sdfsdfsd5329pmnothing));
        
        string IMigrationMetadata.Id
        {
            get { return "201508272004059_[8271sdfsdfsd5329pmnothing]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
